#!/bin/sh

echo "[+] Menambahkan repository Passwall2..."
cat <<EOF >> /etc/opkg/customfeeds.conf
src/gz passwall2 https://master.dl.sourceforge.net/project/openwrt-passwall-build/releases/packages-24.10/aarch64_cortex-a53/passwall2
src/gz passwall_luci https://master.dl.sourceforge.net/project/openwrt-passwall-build/releases/packages-24.10/aarch64_cortex-a53/passwall_luci
src/gz passwall_packages https://master.dl.sourceforge.net/project/openwrt-passwall-build/releases/packages-24.10/aarch64_cortex-a53/passwall_packages
EOF

echo "[+] Mengimpor kunci repo..."
wget -qO /tmp/passwall.pub https://master.dl.sourceforge.net/project/openwrt-passwall-build/passwall.pub
opkg-key add /tmp/passwall.pub && rm -f /tmp/passwall.pub

echo "[+] Update daftar paket dan install luci-app-passwall2..."
opkg update && opkg install --nodeps luci-app-passwall2

echo "[+] Mengganti binary Xray..."
cd /tmp
wget -q https://github.com/BootLoopLover/passwall2/raw/refs/heads/main/xray25.3.31.gz
gunzip xray25.3.31.gz
chmod +x xray25.3.31
[ -f /usr/bin/xray ] && cp /usr/bin/xray /usr/bin/xray.bak
cp xray25.3.31 /usr/bin/xray
rm -f xray25.3.31

echo "[+] Mengatur port TCP redirect (1-65535)..."
uci set passwall2.@global_forwarding[0].tcp_redir_ports='1:65535'
uci commit passwall2

echo "[+] Restart layanan Passwall2..."
/etc/init.d/passwall2 restart

echo "[+] Menambahkan restart Passwall2 saat boot..."
if ! grep -q 'passwall2 restart' /etc/rc.local; then
    sed -i '/^exit 0/i sleep 25\n/etc/init.d/passwall2 restart' /etc/rc.local
fi

echo "[✓] Instalasi Passwall2 selesai!"
