#!/bin/sh

echo "[+] Menambahkan repository Passwall2..."
cat <<EOF >> /etc/opkg/customfeeds.conf
src/gz passwall2 https://master.dl.sourceforge.net/project/openwrt-passwall-build/releases/packages-24.10/aarch64_cortex-a53/passwall2
src/gz passwall_luci https://master.dl.sourceforge.net/project/openwrt-passwall-build/releases/packages-24.10/aarch64_cortex-a53/passwall_luci
src/gz passwall_packages https://master.dl.sourceforge.net/project/openwrt-passwall-build/releases/packages-24.10/aarch64_cortex-a53/passwall_packages
EOF

echo "[+] Mengimpor kunci repo..."
wget -qO /tmp/passwall.pub https://master.dl.sourceforge.net/project/openwrt-passwall-build/passwall.pub
opkg-key add /tmp/passwall.pub && rm -f /tmp/passwall.pub

echo "[+] Update daftar paket dan install luci-app-passwall2..."
opkg update && opkg install --nodeps luci-app-passwall2

echo "[+] Mengganti binary Xray..."
cd /tmp && \
wget -O xray-25.12.2 https://raw.githubusercontent.com/BootLoopLover/xray-stdstrx/refs/heads/main/25.12.2/xray && \
chmod +x xray-25.12.2 && \
[ -f /usr/bin/xray ] && cp /usr/bin/xray /usr/bin/xray.bak && \
cp xray-25.12.2 /usr/bin/xray && \
rm -f xray-25.12.2 && \
echo "✅ Xray Core stdstrx v25.12.2 installed successfully"

echo "[+] Mengatur port TCP redirect (1-65535)..."
uci set passwall2.@global_forwarding[0].tcp_redir_ports='1:65535'
uci commit passwall2

echo "[+] Restart layanan Passwall2..."
/etc/init.d/passwall2 restart

echo "[+] Menambahkan restart Passwall2 saat boot..."
if ! grep -q 'passwall2 restart' /etc/rc.local; then
    sed -i '/^exit 0/i sleep 25\n/etc/init.d/passwall2 restart' /etc/rc.local
fi

echo "[+] Menghapus repository Passwall2 dari daftar feed..."
sed -i '/passwall2/d' /etc/opkg/customfeeds.conf
sed -i '/passwall_luci/d' /etc/opkg/customfeeds.conf
sed -i '/passwall_packages/d' /etc/opkg/customfeeds.conf

echo "[✓] Instalasi Passwall2 selesai!"
